# BEGIN_KITTY_THEME
# Vibrant Ink
include current-theme.conf
# END_KITTY_THEME

window_padding_width 0 5 0 5 
# window_margin_width  0 5 0 5

# Better scrolling
scrollback_lines 20000

# Slight transparency (optional nice)
background_opacity 0.50

# Make new windows inherit cwd (IMPORTANT)
shell_integration enabled

# Disable close confirmation
confirm_os_window_close 0

# Disable bell
enable_audio_bell no

# Faster window resizing redraw
resize_debounce_time 0

# Allow Ctrl+Backspace to delete word (huge QoL)
map ctrl+backspace send_text all \x17

# Open URLs with Ctrl+Click
open_url_with default

# Better font rendering defaults
disable_ligatures never

# font_family JetBrainsMono NF
font_family DepartureMono Nerd Font Mono
bold_font JetBrainsMono NF
font_size 12


# Ctrl+Shift+C/V like GUI apps
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

# Better URL detection
detect_urls yes

# Scroll
map shift+page_up scroll_page_up
map shift+page_down scroll_page_down

# scroll pager 
map ctrl+shift+space show_scrollback
